package sg.edu.ntu.simple_crm;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
// Entity annotation is used to specify that the class is an entity and is
// mapped to a database table.
@Entity
@Table(name = "customer")
public class Customer {
  // private final String id = UUID.randomUUID().toString();
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY) // GenerationType.IDENTITY is used to specify that the primary key
                                                      // is generated by the database.
  @Column(name = "id")
  private Long id;
  @Column(name = "first_name")
  @NotBlank(message = "First name is mandatory")
  private String firstName;
  @Column(name = "last_name")
  private String lastName;
  @Column(name = "email")
  @Email(message = "Email should be valid")
  private String email;
  @Column(name = "contact_no")
  private String contactNo;
  @Column(name = "job_title")
  private String jobTitle;
  @Column(name = "year_of_birth")
  private int yearOfBirth;

  @JsonIgnoreProperties("customer")
  @OneToMany(mappedBy = "customer", cascade = CascadeType.ALL)
  private List<Interaction> interactions;

  public Customer(String firstName, String lastName) {
    this.firstName = firstName;
    this.lastName = lastName;
  }

}
